
version: '3.8'
name: github-stars-viewer
services:
  web:
    build:
      context: ./
      target: runner
    container_name: next-app-prod
    image: github-stars-viewer:prod
    volumes:
      - .:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production