query GetRepositories($before: String, $after: String, $pageSize: Int) {
  search(
    type: REPOSITORY
    query: "is:public stars:>10000 topic:react"
    first: $pageSize
    before: $before
    after: $after
  ) {
    repositoryCount
    pageInfo {
      startCursor
      endCursor
    }
    edges {
      node {
        ... on Repository {
          id
          name
          url
          stargazerCount
          forkCount
        }
      }
    }
  }
}
